############################################################################
# boards/arm/ums9117/qlyx-x30/src/Makefile
############################################################################

include $(TOPDIR)/Make.defs

CSRCS = qlyx_x30_boot.c qlyx_x30_bringup.c

include $(TOPDIR)/boards/Board.mk
